### ISSUE TITLE
MinIO behind https with docker-compose

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#419]
Hello,

Currently, when you deploy [MinIO with docker compose using IM Dashboard](https://im.egi.eu/im-dashboard/configure?selected_tosca=simple-node-disk.yml&childs=minio_compose.yaml) it does it without https ([xref](https://github.com/grycap/ec3/blob/tosca/tosca/artifacts/minio_compose.yml)), which is based on the [MinIO recipe](https://github.com/minio/minio/tree/master/docs/orchestration/docker-compose). It deploys 4 MinIO containers backed by 8 docker volumes, as an attempt to offer high-availability even if they are all sitting on the same host.

Instead, below there is a proposal to do a simpler deployment with just 1 MinIO container backed by 1 docker volume but with [traefik](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-http/) configured to offer https.

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=<your-email@domain.com>"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  minio:
    # taken from: https://github.com/minio/minio/tags
    image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
    volumes:
      - minio-data:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    environment:
      - MINIO_ROOT_USER=<root-user>
      - MINIO_ROOT_PASSWORD=<root-password>
      - MINIO_SERVER_URL=https://<api-endpoint>
      - MINIO_BROWSER_REDIRECT_URL=https://<console-endpoint>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.routers.minio.rule=Host(`<api-endpoint>`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=myresolver"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.rule=Host(`<console-endpoint>`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=myresolver"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

volumes:
  minio-data:

```

I paste it here in case you are interested in adding it to IM Dashboard.

Best regards,
Sebastian
