### ISSUE TITLE
Choosing VM flavors for deployment

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#665]
Hi,

If I provide the specific name of the flavor that I want when deploying a VM with IM-Dashboard, does it also take into account the requested amount of CPUs and memory?

In my opinion, it the flavor is specified, the other values should be ignored.

I am currently facing an issue when I specify a flavor, and deployment returns: `No flavor found for the specified VM requirements.`

Best regards,
Sebastian

**Comment by micafer** [comment]
Yes it is considered.
If you want to avoid issues set very low values in CPU and RAM.

**Comment by sebastian-luna-valero** [comment]
I'd be grateful if you could help with this.

Please join https://aai.egi.eu/auth/realms/id/account/#/enroll?groupPath=/training.egi.eu

Try a deployment using `CESNET-MCCG2` with the TOSCA template below using:
* https://im.egi.eu/im-dashboard/configure?selected_tosca=tosca.yml
* `ubuntu-jammy`

```yaml
description: 'Deploy a compute node getting the IP and SSH credentials to access via
  ssh with an extra HD disk.

  '
imports:
- grycap_custom_types: https://raw.githubusercontent.com/grycap/tosca/main/custom_types.yaml
metadata:
  childs:
  - dydns_egi_update_vm.yml
  - nvidia.yml
  creation_date: 2020-09-08
  display_name: Deploy a VM
  filename: simple-node-disk.yml
  icon: images/vm-icon-disk.png
  infra_name: d4gen1.vm.fedcloud.eu
  order: 1
  tabs:
    DyDNS: nsupdate_.*
    GPU Data: .*gpu.*
    NVIDIA:
    - driver_version
    VM Data:
    - num_cpus
    - mem_size
    - disk_size
    - swap_size
    - instance_type
    - num_instances
    - storage_size
    - mount_path
    - ports
  tag: VM
  template_author: Miguel Caballer
  template_name: VM
  template_version: 1.2.0
topology_template:
  inputs:
    disk_size:
      constraints:
      - valid_values:
        - 20 GiB
        - 50 GiB
        - 100 GiB
        - 200 GiB
        - 0 GiB
      default: 50 GiB
      description: Size of the root disk of the VM (in case of 0 disk will no be resized)
      type: scalar-unit.size
    driver_version:
      default: '535'
      description: NVIDIA Driver version to install
      type: string
    gpu_model:
      default: ''
      description: GPU Model
      type: string
    gpu_vendor:
      constraints:
      - valid_values:
        - ''
        - NVIDIA
        - AMD
      default: NVIDIA
      description: GPU Vendor
      type: string
    instance_type:
      default: a3.16core-60ram-nvidia-t4
      description: Flavor name of the instance
      type: string
    mem_size:
      constraints:
      - valid_values:
        - 4 GiB
        - 8 GiB
        - 16 GiB
        - 32 GiB
        - 64 GiB
        - 128 GiB
        - 256 GiB
        - 512 GiB
        - 2 GiB
      default: 4 GiB
      description: Amount of memory for the VM
      type: scalar-unit.size
    mount_path:
      default: /mnt/disk
      description: Path to mount the extra disk
      type: string
    nsupdate_dns:
      default: d4gen1.vm.fedcloud.eu
      description: DNS hostname registered via https://nsupdate.fedcloud.eu/
      type: string
    nsupdate_password:
      default: nottherealpassword
      description: Secret generated when registering myvm.test.fedcloud.changeme via
        https://nsupdate.fedcloud.eu/
      type: string
    num_cpus:
      constraints:
      - valid_values:
        - 2
        - 4
        - 8
        - 16
        - 32
        - 64
        - 1
      default: 2
      description: Number of virtual cpus for the VM
      type: integer
    num_gpus:
      constraints:
      - valid_values:
        - 0
        - 1
        - 2
        - 3
        - 4
      default: 0
      description: Number of GPUs to assing to this VM
      type: integer
    num_instances:
      default: 1
      description: Number of VMs to be spawned
      type: integer
    ports:
      default:
        port_22:
          protocol: tcp
          source: 22
        port_443:
          protocol: tcp
          source: 443
        port_80:
          protocol: tcp
          source: 80
        port_8800_8900:
          protocol: tcp
          source_range:
          - 8800
          - 8900
      description: 'List of ports to be Opened in the Cloud site (eg. 22,80,443,2000:2100).

        You can also include the remote CIDR (eg. 8.8.0.0/24).

        '
      entry_schema:
        type: PortSpec
      type: map
    storage_size:
      constraints:
      - valid_values:
        - 0 GiB
        - 10 GiB
        - 20 GiB
        - 50 GiB
        - 100 GiB
        - 200 GiB
        - 500 GiB
        - 1 TiB
        - 2 TiB
        - 10 TiB
        - 20 TiB
        - 40 TiB
        - 100 TiB
      default: 2 TiB
      description: Size of the extra HD added to the instance (Set 0 if disk is not
        needed)
      type: scalar-unit.size
    swap_size:
      constraints:
      - valid_values:
        - 0 GiB
        - 4 GiB
        - 8 GiB
        - 16 GiB
        - 32 GiB
        - 64 GiB
        - 128 GiB
        - 256 GiB
        - 512 GiB
      default: 0 GiB
      description: Size of the extra HD added to the instance to use as Swap space
        (Set 0 if it is not needed)
      type: scalar-unit.size
  node_templates:
    dash_ssh_key_simple_node_31:
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/ec3/tosca/tosca/artifacts/add_ssh_key.yml
            inputs:
              ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6NRGgoa77is6YJGo7xJP1awgMjTDC3b39vEfdTDuN85I8YAGluctwxZjCXTuCFJT6XpnD+8k6NFJytzbcX8ZsIwrFJEwW+xexbaYESnlDfYfF+tSyozMJFGCUzt9BC8tpPbK50gKNJ70rlx6I3biXA1JhhFOwVq661ISwID/akNqHb1lX4T4c9xGJKSm/GpN16KH43BtgXpdznQoVJIp/5cwWqJfmpSe2yVBZqJ3eISFlXXbMwuys8MEvyY0xQRvRIB5P+ACjRQyqrnGGP8rYwtVuvPkUrzrKuLK5J1p0xm4t5aYNGrKyL3WQkk1V4qNN+Acb/yQCyVeInJSE+4fF
                sebastian@xps15z
      requirements:
      - host: simple_node
      type: tosca.nodes.ec3.Application
    my_block_storage:
      properties:
        size:
          get_input: storage_size
      type: tosca.nodes.BlockStorage
    nsupdate_host:
      capabilities:
        endpoint:
          properties:
            ports:
              port_http:
                protocol: tcp
                source: 80
              port_https:
                protocol: tcp
                source: 443
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/dydns_egi_update.yml
            inputs:
              dydns_hostname:
                get_input: nsupdate_dns
              dydns_secret:
                get_input: nsupdate_password
              new_ip:
                get_attribute:
                - simple_node
                - public_address
                - 0
      requirements:
      - host: simple_node
      type: tosca.nodes.ec3.Application
    nvidia:
      artifacts:
        nvidia_role:
          file: nvidia.nvidia_driver
          type: tosca.artifacts.AnsibleGalaxy.role
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/nvidia.yml
            inputs:
              nvidia_driver_branch:
                get_input: driver_version
      requirements:
      - host: simple_node
      type: tosca.nodes.SoftwareComponent
    simple_node:
      capabilities:
        endpoint:
          properties:
            network_name: PUBLIC
            ports:
              get_input: ports
        host:
          properties:
            disk_size:
              get_input: disk_size
            gpu_model:
              get_input: gpu_model
            gpu_vendor:
              get_input: gpu_vendor
            instance_type:
              get_input: instance_type
            mem_size:
              get_input: mem_size
            num_cpus:
              get_input: num_cpus
            num_gpus:
              get_input: num_gpus
        os:
          properties:
            image: ost://identity.brno.openstack.cloud.e-infra.cz/b3c5edb5-3002-4554-9cf8-03abbf2a8db0
            type: linux
        scalable:
          properties:
            count:
              get_input: num_instances
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/dummy.yml
      properties:
        instance_name: d4gen1.vm.fedcloud.eu_simple_node
      requirements:
      - local_storage:
          capability: tosca.capabilities.Attachment
          node: my_block_storage
          relationship:
            properties:
              location:
                get_input: mount_path
            type: tosca.relationships.AttachesTo
      - local_storage:
          capability: tosca.capabilities.Attachment
          node: swap_storage
          relationship:
            properties:
              fs_type: swap
              location: swap
            type: tosca.relationships.indigo.AttachesTo
      type: tosca.nodes.indigo.Compute
    swap_storage:
      properties:
        size:
          get_input: swap_size
      type: tosca.nodes.BlockStorage
  outputs:
    node_creds:
      value:
        get_attribute:
        - simple_node
        - endpoint
        - credential
        - 0
    node_ip:
      value:
        get_attribute:
        - simple_node
        - public_address
        - 0
    nsupdate_dns:
      value:
        get_input:
        - nsupdate_dns
tosca_definitions_version: tosca_simple_yaml_1_0
```
